public class AuditTrailUtil {

    //Audit Trail Types
    public static final String GTC_TYPE = 'Online Approval of GTC';
    public static final String BUYER_REQUEST_TYPE = 'Buyer Request Signature';
    public static final String SUPPLIER_REQUEST_TYPE = 'Supplier Request Signature';
    
    //Audit Trail File Name
    public static final String BUYER_REQUEST_FILE = 'Buyer Request Signature.pdf';
    public static final String SUPPLIER_REQUEST_FILE = 'Supplier Request Signature.pdf';

    //Audit Trail Email Template
    public static final String EMAIL_TEMPLATE_BUYER_REQUEST = 'Buyer Request Signature';
    public static final String EMAIL_TEMPLATE_SUPPLIER_REQUEST = 'Supplier Request Signature';

    //Email Attachment
    public static final String EMAIL_FROM = 'operations@incomlend.com';

    public static final String EMAIL_CC = 'operations@incomlend.com';
    

}